[package]
name = "cont-arith-code"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

logaddexp = "0.1.3"
libm = "0.2.8" # expm1, erf
statrs = "0.18.0" # erf_inv
errorfunctions = "0.2.0" # erfc, erfcx
